### ISSUE TITLE
Interceptors do not work if backend url is not the same as the frontend one.

### ISSUE THREAD

**Issue by SetupCoding** [valendres/playwright-msw#42]
Currently, if your frontend runs on `http://localhost:3000` and your backend runs on `http://localhost:8080`

Requests like `http://localhost:8080/api/users` will not be intercepted, even if the handler route is defined like `*/api/users`.

Is there some way to properly configure the backend url, so that the MSW interceptors work again?

**Comment by valendres** [comment]
Hey @SetupCoding, thanks for raising this. This is definitely not intended. I'll look into what can be done to resolve this issue.

Are you happy if I make it so that rest.get("http://localhost:8080/api/users") works, or do you want to be able to somehow specify a backend url when calling `createWorkerFixture`?

p.s. sorry for the delay. I recently moved to the US and haven't had much time to look at the library.

**Comment by SetupCoding** [comment]
Hey @valendres,
No worries! Thanks for your reply.

I think the best way would be to make it work as in MSW.
`*/api/users` (with a wildcard) would solve it for me, which is the way MSW handles routes. 

Explicitly specifying the entire backend URL could also be nice but is not necessarily required for me.

Many thanks!

**Comment by valendres** [comment]
I created a PR (https://github.com/valendres/playwright-msw/pull/44) that should allow you to use `*/api/users` :)

**Comment by valendres** [comment]
@SetupCoding [playwright-msw@2.1.0](https://www.npmjs.com/package/playwright-msw/v/2.1.0) has been published to address this issue :)

**Comment by SetupCoding** [comment]
Perfect! Thanks a lot!
